@version=v1

### Create Game
POST {{baseUrl}}/api/{{version}}/Games
Content-Type: application/json

{
  "name": "Test",
  "options": {
    "shareOtherPlayerTrackers": true
  },
  "trackers": [
    {
      "name": "Score",
      "startingValue": "0"
    }
  ]
}

> {% client.global.set("entryCode", response.body.entryCode); %}

### Join Game
POST {{baseUrl}}/api/{{version}}/Games/Join
Content-Type: application/json

{
  "entryCode": "{{entryCode}}",
  "name": "Player 1",
  "observer": false
}

> {% 
    client.global.set("gameId", response.body.gameId);
    client.global.set("token", response.body.token);
 %}

### Get Game
GET {{baseUrl}}/api/{{version}}/Games/{{gameId}}
Authorization: Bearer {{token}}

### Get Game Players
GET {{baseUrl}}/api/{{version}}/Games/{{gameId}}/Players
Authorization: Bearer {{token}}

### Start Game
POST {{baseUrl}}/api/{{version}}/Games/{{gameId}}/Start
Authorization: Bearer {{token}}

### End Game
POST {{baseUrl}}/api/{{version}}/Games/{{gameId}}/End
Authorization: Bearer {{token}}

### Get Game Summary
GET {{baseUrl}}/api/{{version}}/Games/{{gameId}}/Summary
Authorization: Bearer {{token}}

### Metrics
GET {{baseUrl}}/metrics

### Version
GET {{baseUrl}}/version

### SignalR Negotiate
POST {{baseUrl}}/hubs/game/negotiate?negotiateVersion=1
Authorization: Bearer {{token}}

> {%
    client.global.set("signalrtoken", response.body.connectionToken);
%}

### SignalR Hub
WEBSOCKET ws://localhost:5000/hubs/game?id={{signalrtoken}}&access_token={{token}}
Content-Type: application/json // We use it for highlighting

===
{"protocol":"json","version":1}
=== wait-for-server
{"type":6}
===
{"arguments":[],"invocationId":"0","target":"Heartbeat","type":1}
=== wait-for-server